package br.edu.eseg.brproject.model;

// Generated May 29, 2011 12:04:47 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Matrizprioristakeholder generated by hbm2java
 */
@Entity
@Table(name = "notastakeholder" )
public class Notastakeholder implements java.io.Serializable {

	private Long id;
	private Stakeholder stakeholderavaliado;
	private Stakeholder stakeholderavaliador;
	private Nota nota;
	private Projeto projeto;

	public Notastakeholder() {
	}

	public Notastakeholder(Stakeholder stakeholderavaliado,
			Stakeholder stakeholderavaliador,
			Nota nota) {
		this.stakeholderavaliado = stakeholderavaliado;
		this.stakeholderavaliador = stakeholderavaliador;
		this.nota = nota;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "stakeholderavaliadoid", nullable = false)
	@NotNull
	public Stakeholder getStakeholderavaliado() {
		return this.stakeholderavaliado;
	}

	public void setStakeholderavaliado(Stakeholder stakeholderavaliado) {
		this.stakeholderavaliado = stakeholderavaliado;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "stakeholderavaliadorid", nullable = false)
	@NotNull
	public Stakeholder getStakeholderavaliador() {
		return this.stakeholderavaliador;
	}

	public void setStakeholderavaliador(Stakeholder stakeholderavaliador) {
		this.stakeholderavaliador = stakeholderavaliador;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "notaid", nullable = false)
	@NotNull
	public Nota getNota() {
		return this.nota;
	}

	public void setNota(
			Nota nota) {
		this.nota = nota;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "projetoid", nullable = false)
	@NotNull
	public Projeto getProjeto() {
		return projeto;
	}

	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}
	
	

}