package br.edu.eseg.brproject.model;

// Generated May 29, 2011 12:04:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Prioridadestakeholder generated by hbm2java
 */
@Entity
@Table(name = "nota" )
public class Nota implements java.io.Serializable {

	private Long id;
	private String nome;
	private Double valor;
	private Set<Notastakeholder> notastakeholders = new HashSet<Notastakeholder>(0);

	public Nota() {
	}

	public Nota(String nome, Double valor,
			Set<Notastakeholder> matrizprioristakeholders) {
		this.nome = nome;
		this.valor = valor;
		this.notastakeholders = matrizprioristakeholders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "valor", precision = 22, scale = 0)
	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nota")
	public Set<Notastakeholder> getNotastakeholders() {
		return this.notastakeholders;
	}

	public void setNotastakeholders(
			Set<Notastakeholder> notastakeholders) {
		this.notastakeholders = notastakeholders;
	}

}
