package br.edu.eseg.brproject.model;

// Generated May 29, 2011 12:04:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Recurso generated by hbm2java
 */
@Entity
@Table(name = "recurso" )
public class Recurso implements java.io.Serializable {

	private Long id;
	private Tiporecurso tiporecurso;
	private String nome;
	private Set<Utilizacaorecurso> utilizacaorecursos = new HashSet<Utilizacaorecurso>(
			0);

	public Recurso() {
	}

	public Recurso(Tiporecurso tiporecurso, String nome,
			Set<Utilizacaorecurso> utilizacaorecursos) {
		this.tiporecurso = tiporecurso;
		this.nome = nome;
		this.utilizacaorecursos = utilizacaorecursos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tiporecursoid")
	public Tiporecurso getTiporecurso() {
		return this.tiporecurso;
	}

	public void setTiporecurso(Tiporecurso tiporecurso) {
		this.tiporecurso = tiporecurso;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recurso")
	public Set<Utilizacaorecurso> getUtilizacaorecursos() {
		return this.utilizacaorecursos;
	}

	public void setUtilizacaorecursos(Set<Utilizacaorecurso> utilizacaorecursos) {
		this.utilizacaorecursos = utilizacaorecursos;
	}

}
