package br.edu.eseg.brproject.model;

// Generated May 29, 2011 12:04:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * Recurso generated by hbm2java
 */
@Entity
@Table(name = "recurso")
public class Recurso implements java.io.Serializable {

	private Long id;
	private Tiporecurso tiporecurso;
	private String nome;
	private Projeto projeto;
	private Set<Utilizacaorecurso> utilizacaorecursos = new HashSet<Utilizacaorecurso>(
			0);

	public Recurso() {
	}

	public Recurso(Tiporecurso tiporecurso, String nome,
			Set<Utilizacaorecurso> utilizacaorecursos) {
		this.tiporecurso = tiporecurso;
		this.nome = nome;
		this.utilizacaorecursos = utilizacaorecursos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tiporecursoid")
	public Tiporecurso getTiporecurso() {
		return this.tiporecurso;
	}

	public void setTiporecurso(Tiporecurso tiporecurso) {
		this.tiporecurso = tiporecurso;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projetoid", nullable = false)
	@NotNull
	public Projeto getProjeto() {
		return projeto;
	}

	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recurso")
	public Set<Utilizacaorecurso> getUtilizacaorecursos() {
		return this.utilizacaorecursos;
	}

	public void setUtilizacaorecursos(Set<Utilizacaorecurso> utilizacaorecursos) {
		this.utilizacaorecursos = utilizacaorecursos;
	}

	@Override
	public int hashCode() {
		if (id != null) {
			return id.hashCode();
		}
		return super.hashCode();
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Recurso) {
			Recurso r = (Recurso) obj;
			if (id != null && r.id != null) {
				return id.equals(r.id);
			}
		}
		return super.equals(obj);
	}
}
