package br.edu.eseg.brproject.model;

// Generated May 29, 2011 12:04:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Statusmudanca generated by hbm2java
 */
@Entity
@Table(name = "statusmudanca" )
public class Statusmudanca implements java.io.Serializable {

	private Long id;
	private String nome;
	private Set<Solicitacaomudanca> solicitacaomudancas = new HashSet<Solicitacaomudanca>(
			0);

	public Statusmudanca() {
	}

	public Statusmudanca(String nome,
			Set<Solicitacaomudanca> solicitacaomudancas) {
		this.nome = nome;
		this.solicitacaomudancas = solicitacaomudancas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusmudanca")
	public Set<Solicitacaomudanca> getSolicitacaomudancas() {
		return this.solicitacaomudancas;
	}

	public void setSolicitacaomudancas(
			Set<Solicitacaomudanca> solicitacaomudancas) {
		this.solicitacaomudancas = solicitacaomudancas;
	}

}
