package br.edu.eseg.brproject.model;

// Generated May 29, 2011 12:04:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Statusprojeto generated by hbm2java
 */
@Entity
@Table(name = "statusprojeto" )
public class Statusprojeto implements java.io.Serializable {

	private Long id;
	private String nome;
	private Set<Projeto> projetos = new HashSet<Projeto>(0);
	private Set<Arquivo> arquivos = new HashSet<Arquivo>(0);

	public Statusprojeto() {
	}
	
	public Statusprojeto(Long id){
		this.id = id;
	}

	public Statusprojeto(String nome, Set<Projeto> projetos) {
		this.nome = nome;
		this.projetos = projetos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusprojeto")
	public Set<Projeto> getProjetos() {
		return this.projetos;
	}

	public void setProjetos(Set<Projeto> projetos) {
		this.projetos = projetos;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusprojeto")
	public Set<Arquivo> getArquivos() {
		return arquivos;
	}
	
	public void setArquivos(Set<Arquivo> arquivos) {
		this.arquivos = arquivos;
	}

}
