package br.edu.eseg.brproject.model;

// Generated May 29, 2011 12:04:47 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtilizacaorecursoId generated by hbm2java
 */
@Embeddable
public class UtilizacaorecursoId implements java.io.Serializable {

	private long recursoid;
	private long tarefaid;

	public UtilizacaorecursoId() {
	}

	public UtilizacaorecursoId(long recursoid, long tarefaid) {
		this.recursoid = recursoid;
		this.tarefaid = tarefaid;
	}

	@Column(name = "recursoid", nullable = false)
	public long getRecursoid() {
		return this.recursoid;
	}

	public void setRecursoid(long recursoid) {
		this.recursoid = recursoid;
	}

	@Column(name = "tarefaid", nullable = false)
	public long getTarefaid() {
		return this.tarefaid;
	}

	public void setTarefaid(long tarefaid) {
		this.tarefaid = tarefaid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtilizacaorecursoId))
			return false;
		UtilizacaorecursoId castOther = (UtilizacaorecursoId) other;

		return (this.getRecursoid() == castOther.getRecursoid())
				&& (this.getTarefaid() == castOther.getTarefaid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRecursoid();
		result = 37 * result + (int) this.getTarefaid();
		return result;
	}

}
